[logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log

[libdefaults]
    default_realm = RANSOM.NET
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    forwardable = true
    udp_preference_limit = 1
    # solve the docker dns issue
    # force kerberos to use default realm name `RANSOM.NET`
    # otherwise it tries to visit realm named `ANTI-RANSOMWARE_RANDOM_NET`
    rdns = false 
    dns_canonicalize_hostname = false

[realms]
    RANSOM.NET = {
        kdc = kdc-server:88
        admin_server = kdc-server:749
        default_domain = ransom.net
    }

[domain_realm]
    .ransom.net = RANSOM.NET
    ransom.net = RANSOM.NET