# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61\x63kup.proto\x12\x06\x62\x61\x63kup\"*\n\x14StartRecoveryRequest\x12\x12\n\ncommand_id\x18\x01 \x01(\t\"1\n\x12StartRecoveryReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2Z\n\rBackupStorage\x12I\n\rStartRecovery\x12\x1c.backup.StartRecoveryRequest\x1a\x1a.backup.StartRecoveryReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backup_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTRECOVERYREQUEST']._serialized_start=24
  _globals['_STARTRECOVERYREQUEST']._serialized_end=66
  _globals['_STARTRECOVERYREPLY']._serialized_start=68
  _globals['_STARTRECOVERYREPLY']._serialized_end=117
  _globals['_BACKUPSTORAGE']._serialized_start=119
  _globals['_BACKUPSTORAGE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
