# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common import lockdown_pb2 as lockdown__pb2


class LockdownServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerLockdown = channel.unary_unary(
                '/common.LockdownService/TriggerLockdown',
                request_serializer=lockdown__pb2.LockdownRequest.SerializeToString,
                response_deserializer=lockdown__pb2.LockdownResponse.FromString,
                )


class LockdownServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TriggerLockdown(self, request, context):
        """Detection calls this on Backup and Clients
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockdownServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerLockdown': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerLockdown,
                    request_deserializer=lockdown__pb2.LockdownRequest.FromString,
                    response_serializer=lockdown__pb2.LockdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'common.LockdownService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LockdownService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TriggerLockdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/common.LockdownService/TriggerLockdown',
            lockdown__pb2.LockdownRequest.SerializeToString,
            lockdown__pb2.LockdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
