# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import recovery_pb2 as recovery__pb2


class RecoveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerRecovery = channel.unary_unary(
                '/common.RecoveryService/TriggerRecovery',
                request_serializer=recovery__pb2.RecoveryRequest.SerializeToString,
                response_deserializer=recovery__pb2.RecoveryResponse.FromString,
                )


class RecoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TriggerRecovery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerRecovery': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerRecovery,
                    request_deserializer=recovery__pb2.RecoveryRequest.FromString,
                    response_serializer=recovery__pb2.RecoveryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'common.RecoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecoveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TriggerRecovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/common.RecoveryService/TriggerRecovery',
            recovery__pb2.RecoveryRequest.SerializeToString,
            recovery__pb2.RecoveryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
