# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recovery.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erecovery.proto\x12\x06\x63ommon\"%\n\x0fRecoveryRequest\x12\x12\n\ncommand_id\x18\x01 \x01(\t\"4\n\x10RecoveryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2W\n\x0fRecoveryService\x12\x44\n\x0fTriggerRecovery\x12\x17.common.RecoveryRequest\x1a\x18.common.RecoveryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recovery_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECOVERYREQUEST']._serialized_start=26
  _globals['_RECOVERYREQUEST']._serialized_end=63
  _globals['_RECOVERYRESPONSE']._serialized_start=65
  _globals['_RECOVERYRESPONSE']._serialized_end=117
  _globals['_RECOVERYSERVICE']._serialized_start=119
  _globals['_RECOVERYSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
