# generate fake data for 2 departments.
import os
import csv
import random
import json
from faker import Faker

fake = Faker()

# root
BASE_DIR = "./simulation_data"


def ensure_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)


# finance
# number and text, low-entropy data
def gen_finance_data(num_files=10):
    target_dir = os.path.join(BASE_DIR, "finance")
    ensure_dir(target_dir)
    print(f"💰 Generating Finance Data in {target_dir}...")

    # salary data
    for i in range(num_files):
        filename = os.path.join(target_dir, f"payroll_2024_Q{i+1}.csv")
        with open(filename, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["Employee ID", "Name", "Department", "Salary", "IBAN"])
            for _ in range(100):  # 100 行数据
                writer.writerow(
                    [
                        fake.uuid4()[:8],
                        fake.name(),
                        "Finance",
                        random.randint(50000, 150000),
                        fake.iban(),
                    ]
                )

    # contract data
    for i in range(5):
        filename = os.path.join(target_dir, f"contract_{fake.company().replace(' ', '_')}.txt")
        with open(filename, "w") as f:
            f.write(f"CONTRACT AGREEMENT\n\nDate: {fake.date()}\n\n")
            f.write(fake.text(max_nb_chars=2000))


# rnd
# code, config, structured, low-entropy
def gen_rnd_data(num_files=10):
    target_dir = os.path.join(BASE_DIR, "rnd")
    ensure_dir(target_dir)
    print(f"💻 Generating R&D Data in {target_dir}...")

    # code, python
    for i in range(num_files):
        filename = os.path.join(target_dir, f"module_{i}_logic.py")
        with open(filename, "w") as f:
            f.write(f"# Auto-generated by R&D Dept\nimport os\nimport sys\n\n")
            f.write(f"class {fake.word().capitalize()}Service:\n")
            f.write(f"    def __init__(self):\n")
            f.write(f"        self.config = '{fake.sha256()}'\n")
            for _ in range(20):
                f.write(f"    # {fake.sentence()}\n")
                f.write(f"    def process_{fake.word()}(self):\n")
                f.write(f"        return {random.random()}\n\n")

    # config, json
    for i in range(5):
        filename = os.path.join(target_dir, f"config_{fake.word()}.json")
        data = {
            "service_name": fake.word(),
            "version": "1.0.4",
            "db_host": fake.ipv4(),
            "features": [fake.word() for _ in range(10)],
            "debug_mode": random.choice([True, False]),
        }
        with open(filename, "w") as f:
            json.dump(data, f, indent=4)


# high-entropy file, compressed or images
# to test false positive
def gen_high_entropy_files():
    target_dir = os.path.join(BASE_DIR, "rnd/assets")
    ensure_dir(target_dir)
    print(f"Generating High Entropy Assets (Images/Zips)...")

    for i in range(3):
        filename = os.path.join(target_dir, f"logo_v{i}.jpg")
        with open(filename, "wb") as f:
            f.write(os.urandom(1024 * 20))


if __name__ == "__main__":
    gen_finance_data()
    gen_rnd_data()
    print("\nData Generation Complete!")
