# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lockdown.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elockdown.proto\x12\x08security\"^\n\x0fLockdownRequest\x12\x11\n\tthreat_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x15\n\rtargeted_node\x18\x04 \x01(\t\";\n\x10LockdownResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t2]\n\x0fLockdownService\x12J\n\x0fTriggerLockdown\x12\x19.security.LockdownRequest\x1a\x1a.security.LockdownResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lockdown_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOCKDOWNREQUEST']._serialized_start=28
  _globals['_LOCKDOWNREQUEST']._serialized_end=122
  _globals['_LOCKDOWNRESPONSE']._serialized_start=124
  _globals['_LOCKDOWNRESPONSE']._serialized_end=183
  _globals['_LOCKDOWNSERVICE']._serialized_start=185
  _globals['_LOCKDOWNSERVICE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
